In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.asd_node_interactivity = "all"

In [2]:
import numpy as np

In [3]:
def isint(s):
    try:
        int(s)
        return True
    except(ValueError, TypeError):
        return False

$$ Задание 1.1 $$
Расчет по фомуле: $y = \frac{\sin\frac{pi}{6} + \sqrt{3 + x^2} - \ln{(x - 1)^3}}{arcsin\frac{x}{2}}$, при $x = 1.59$

In [4]:
x = 1.59
y = (np.sin(np.pi/6) + np.sqrt(3 + x**2) - np.log(x - 1)**3) / np.arcsin(x/2)
print("{:.3f}" .format(y))

3.262


$$ Задание 1.2 $$
Найти оценки уравнения регрессии, используя метод наименьших квадратов и матричную форму записи уравнений: $$ A = (X^T * X)^{-1} * (X^T * Y) $$

In [5]:
x = np.zeros(shape=(12, 3), dtype=int)
x[:, 0] = 1
N = input("N = ")
if isint(N):
    N = int(N)
    for i in range(12):
        x[i, 1] = np.random.randint(N, N+12)
        x[i, 2] = np.random.randint(60, 82)
    Y = np.random.uniform(13.5, 18.6, 12).reshape(12, 1)
    A = (np.linalg.matrix_power(np.transpose(x).dot(x), -1)).dot(np.transpose(x).dot(Y))
    print("Матрица после вычисления: \n", A)
    Z = A[0] * x[:, 0] + A[1] * x[:, 1] + A[2] * x[:, 2]
    print("Значение Y после формулы: \n", Z.reshape(12, 1))
    print("Исходное значени Y: \n", Y)
else:
    print("Введите целое число")

N =  20


Матрица после вычисления: 
 [[ 1.40290782e+01]
 [-7.08564215e-03]
 [ 3.65864946e-02]]
Значение Y после формулы: 
 [[16.72101325]
 [16.40706437]
 [16.15688626]
 [16.8001136 ]
 [16.42123565]
 [16.19231447]
 [16.19231447]
 [16.36931959]
 [16.11914148]
 [16.51450728]
 [16.04712678]
 [16.82961445]]
Исходное значени Y: 
 [[17.49155688]
 [17.48769196]
 [15.49994882]
 [14.7183323 ]
 [15.25807858]
 [14.35583553]
 [17.7757565 ]
 [13.82312144]
 [15.93213131]
 [18.23806495]
 [17.7865596 ]
 [18.40357377]]
